package Modele;
// default package
// Generated 10 mars 2011 17:57:40 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal userId;
	private String userLogin;
	private String userPassword;
	private BigDecimal userEstProf;

	public Utilisateur() {
	}

	public Utilisateur(BigDecimal userId) {
		this.userId = userId;
	}

	public Utilisateur(BigDecimal userId, String userLogin,
			String userPassword, BigDecimal userEstProf) {
		this.userId = userId;
		this.userLogin = userLogin;
		this.userPassword = userPassword;
		this.userEstProf = userEstProf;
	}

	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public BigDecimal getUserEstProf() {
		return this.userEstProf;
	}

	public void setUserEstProf(BigDecimal userEstProf) {
		this.userEstProf = userEstProf;
	}

	public boolean estProf () {
		if (this.userEstProf == BigDecimal.ONE) return true;
		return false;
	}
}
